version: '3.2'
services:
  app:
    container_name: hapijs-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    links:
      - mongo-db
    environment:
      - PORT=8081
      - HOST=0.0.0.0
      - LOG_LEVEL=error
      - MONGODB_URL=mongodb://mongo-db:27017/settle
      - MONGODB_USER=root
      - MONGODB_PASSWORD=0000
      - MONGOOSE_DEBUG=false
      - PAGINATOR_LIMIT=10
      - PAGINATOR_PAGE=1
      - CURRENCIES=EUR,USD,BRL,ARS
      - FIXER_URL=https://data.fixer.io/api/convert
      - FIXER_API_KEY=824e753b9d8f1bf170e5adf80e7788e9
      - RESPONSE_TTL=24h #10m #must to be

  mongo-db:
    container_name: mongo-db
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=0000
    ports:
      - '27017:27017'
    volumes:
      - ./db:/data/db

volumes:
  db:
